import party from '../assets/images/party.jpg';
import eventplanning from '../assets/images/event_planning.jpg';
import bride_groom from '../assets/images/bride_and_groom.jpg';
import wedding1 from '../assets/images/enchanted_wedding1.jpg';
import wedding2 from '../assets/images/enchanted_wedding2.jpg';
import wedding3 from '../assets/images/enchanted_wedding3.jpg';
import wedding4 from '../assets/images/enchanted_wedding4.jpg';
import birtday1 from '../assets/images/great_gatsby1.jpg';
import birtday2 from '../assets/images/great_gatsby2.jpg';
import birtday3 from '../assets/images/great_gatsby3.jpg';
import babyBirthday1 from '../assets/images/candyland1.jpg';
import babyBirthday2 from '../assets/images/candyland2.jpg';
import babyBirthday3 from '../assets/images/candyland3.jpg';
import babyBirthday4 from '../assets/images/candyland4.jpg';
import babyBirthday5 from '../assets/images/candyland5.jpg';
import babyBirthday6 from '../assets/images/candyland6.jpg';
import wedding from '../assets/images/wedding.jpg';
import cake from '../assets/images/cake.jpg';
import location1 from '../assets/images/location.jpg';
import location2 from '../assets/images/location2.jpg';
import themeParty from '../assets/images/themeparty.jpg';
import bombonniere from '../assets/images/bomboniere.jpg';
import baptism from '../assets/images/battesimo.jpg';
import buffet from '../assets/images/buffet.jpg';

const Wedding = [bride_groom, wedding1, wedding2, wedding3, wedding4];
const Birthday = [birtday1, birtday2, birtday3];
const BabyBirthday = [babyBirthday1, babyBirthday2, babyBirthday3, babyBirthday4, babyBirthday5, babyBirthday6];
const homeImages = [wedding, themeParty, cake, location1, location2, bombonniere, baptism, buffet];
export { eventplanning, Wedding, Birthday, party, BabyBirthday, homeImages };